version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.16.0
    steps:
      - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Install node dependencies"
          command: "npm install"
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run test-with-coverage
      - store_artifacts:
          path: coverage